
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezosqcqzbezdhshopslf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6b3NxY3F6YmV6ZGhzaG9wc2xmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MDk5NTQsImV4cCI6MjA2NjA4NTk1NH0.TAkK9PflYdp4iCQKVmxyanMwGGkSJS9Cw9GLo5_CPNU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
